/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/* Include Files */
#define SCRIPT_REALNAME "kisbox"
#include "../headers/define.h"
#include "../sfall/lib.math.h"
#define NAME                    SCRIPT_KISBOX
#include "../headers/command.h"

/* Sets whether the door is locked or trapped */
#define LOCKED_STATUS                   STATE_ACTIVE
#define TRAPPED_STATUS                  STATE_INACTIVE
#define DOOR_STATUS                     STATE_METAL
#define LOCK_STATUS                     STATE_STANDARD_LOCK

#define custom_start
#define custom_map_enter_p_proc
#define custom_map_update_p_proc
#include "../headers/containers.h"

#define LVAR_Restock_Time               (7)
#define LVAR_Restock_Time_Fix           (8) //added by killap

import variable klam_sajag_box_obj;

procedure start begin
   klam_sajag_box_obj := self_obj;
end

procedure map_enter_p_proc begin
   klam_sajag_box_obj := self_obj;
   if (local_var(LVAR_Set_Door_Status) == 0) then begin
       set_local_var(LVAR_Set_Door_Status,1);
       set_local_var(LVAR_Locked,LOCKED_STATUS);
       set_local_var(LVAR_Trapped,TRAPPED_STATUS);
   end

   if (unsigned_int_compare(local_var(LVAR_Restock_Time), game_time) < 0) then begin
      variable tmp_box := move_quest_items();
      check_restock_item(PID_BOTTLE_CAPS, 125, 250, 100)
      check_restock_item(PID_POWERED_ARMOR, 1, 1, 100)
      check_restock_item(PID_KNIFE, 1, 2, 100)
      check_restock_item(PID_THROWING_KNIFE, 2, 4, 100)
      check_restock_item(PID_10MM_JHP, 0, 3, 100)
      check_restock_item(PID_STIMPAK, 2, 4, 100)
      check_restock_item(PID_SUPER_STIMPAK, 1, 2, 100)
      check_restock_item(PID_MEAT_JERKY, 3, 4, 100)
      check_restock_item(PID_BEER, 3, 6, 100)
      check_restock_item(PID_BOOZE, 2, 4, 100)
      check_restock_item(PID_LEATHER_ARMOR, 0, 1, 50)
      check_restock_item(PID_10MM_PISTOL, 0, 1, 100)
      check_restock_item(PID_SPEAR, 1, 2, 100)
      check_restock_item(PID_M72_GAUSS_RIFLE, 0, 2, 100)
      check_restock_item(PID_RADAWAY, 0, 2, 100)
      call restore_critical_items(tmp_box);
      set_local_var(LVAR_Restock_Time, (2 * ONE_GAME_DAY) + game_time);
   end

   if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
       obj_lock(self_obj);
   end
   else begin
       obj_unlock(self_obj);
   end
end

procedure map_update_p_proc begin
   klam_sajag_box_obj := self_obj;
   if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
       obj_lock(self_obj);
   end
   else begin
       obj_unlock(self_obj);
   end
end
