#include "sfall.h"

#define PID_SARGT_KEYCARD (601)
#define LVAR_unlocked     (0)

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
  if (local_var(LVAR_unlocked) == 0) then begin
    obj_lock(self_obj);
  end
end

procedure use_p_proc begin
  if (obj_is_locked(self_obj)) then begin
    script_overrides;
    display_msg("The door is locked.");
  end
end

procedure use_obj_on_p_proc begin
  if (obj_pid(obj_being_used_with) == PID_SARGT_KEYCARD) then begin
    script_overrides;
    set_local_var(LVAR_unlocked, 1);
    obj_unlock(self_obj);
    display_msg("The lock clicks open.");
  end
end
