#
#
#
#
#
{0}{}{Game Preferences}
{1}{}{Screen Settings}



{50}{}{Screen Settings}
{51}{}{Custom}
{52}{}{Width}
{53}{}{Height}
{54}{}{Done}
{55}{}{Cancel}
{56}{}{Fallout must restart to apply settings.}
{57}{}{Would you like to restart Fallout now?}


{100}{}{Hi-Res}
{101}{}{RESOLUTION}
{102}{}{Colours}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Change Side-Bar Art}


{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Off}
{204}{}{Fullscreen}
{205}{}{Window}
{206}{}{GPU Blitting}
